env:
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-var:
    - 2
  no-console:
    - 0

  dot-location:
    - 2
    - "property"

  brace-style:
    - 2
    - "1tbs"
